# src/scene_beat_agent.py
# to unit test, run as module in the terminal from the project root:
  # $ python3 -m src.scene_beat_agent
# ^^This uses pre-generated dummy_data.json, generated by running the narrative design agent as module from the terminal

from pydantic import BaseModel, Field, ValidationError
from typing import Literal, Optional
from agents import Agent, Runner, RunResult, ModelSettings, RunContextWrapper
from openai.types.shared.reasoning import Reasoning
from pathlib import Path
from dotenv import load_dotenv
import sys
import asyncio

# LOCAL MODULES
SRC_ROOT: Path = Path(__file__).parent # the src/ folder
sys.path.insert(0, str(SRC_ROOT))

from narrative_design_agent import NarrativeDesignOutputSchema, SceneData

load_dotenv()

class SceneBeat(BaseModel):
    beat_index: int = Field(...,description="1-based position of this beat in the scene.")
    beat_name: str = Field(...,description="Stable beat name, for example act1_scene1_beat_01.")
    purpose: str = Field(...,description="Why this beat exists in the scene.")
    summary: str = Field(...,description="What happens in this beat, in 1-3 sentences.")
    location_uuid: str = Field(...,description="The UUID of the location where this beat takes place.")
    present_character_uuids: list[str] = Field(
        description="Player character UUID plus UUIDs of any NPCs actively present in the beat."
    )
    focal_character_uuid: Optional[str] = Field(
        default=None,
        description="The character driving the beat emotionally or narratively."
    )
    mood: str = Field(description="The emotional tone of the beat.")
    revelation: Optional[str] = Field(
        default=None,
        description="New information learned in this beat, if any."
    )
    tension_change: Literal["rise", "fall", "twist", "hold"] = Field(
        description="How this beat changes dramatic tension."
    )
    player_goal: Optional[str] = Field(
        default=None,
        description="What the player character is trying to do in this beat."
    )
    interactive: bool = Field(
        description="Whether this beat contains a player choice or interactive moment."
    )
    choice_prompt: Optional[str] = Field(
        default=None,
        description="Short description of the player decision, if interactive."
    )
    branch_outcomes: Optional[list[str]] = Field(
        default=None,
        description="High-level outcomes for the available choices, if interactive."
    )
    exit_state: str = Field(
        description="What has changed by the end of the beat."
    )

class SceneBeatSheet(BaseModel):
    story_title: str = Field(...,description="The title of the story")
    scene_name: str = Field(...,description="The human-readable, unique and stable ID for this scene.")
    scene_uuid: str = Field(...,description="The UUID for this scene.")
    source_scene_summary: str = Field(...,description="The narrative summary of this scene.")
    location_name: str = Field(...,description="The human-readable name of this scene's location")
    location_uuid: str = Field(...,description="The UUID of this scene's location")
    player_character_uuid: str = Field(...,description="The UUID of the player character")
    non_player_character_uuids: list[str] = Field(description="A list of the UUIDs for the non-player characters in this scene")
    dramatic_question: str = Field(
        description="The core uncertainty driving the scene."
    )
    scene_goal: str = Field(
        description="What the player character wants in the scene."
    )
    scene_turn: str = Field(
        description="What changes by the end of the scene."
    )
    beats: list[SceneBeat] = Field(
        description="Ordered beat list for this scene, usually 5-8 beats."
    )

def get_sb_agent_input(
        nd_spec: NarrativeDesignOutputSchema,
        scene_uuid: str
) -> str:
    # extract all the relevant data from the context
    scene_catalog       = nd_spec.get_scene_catalog() # scenes indexed by UUID
    if not scene_uuid in scene_catalog:
        raise ValueError ("scene_uuid not in catalogue")
    scene_data: SceneData = SceneData.model_validate(scene_catalog[scene_uuid])
    scene_name: str = scene_data.scene_name
    narrative_summary: str = scene_data.narrtive_summary
    
    # write the promt string
    prompt_str = f"""Write the scene beats for {scene_name}.
Scene UUID: {scene_uuid}
Here is the scene's narrative summary from the Narrative Designer: {narrative_summary}"""
    
    return prompt_str

def get_sb_agent_instructions(
        wrapper: RunContextWrapper[NarrativeDesignOutputSchema],
        agent: Agent[NarrativeDesignOutputSchema]
) -> str:
    return f"""You are part of the narrative design team at a game studio that makes visual novel games in RenPy. Your specific job is to write scene beats.
For each scene, you create ordered beats, emptional turns, and choice opportunities that enrich the gameplay experience and preserve end-to-end narrative continuity.
Here is the story plan for the game you are currently working on, this is your context:\n
{wrapper.context.model_dump_json()}
"""

class SceneBeatAgent():
    
    async def run_workflow(self, in_json: str, scene_uuid: str) -> SceneBeatSheet:
        try:
            nd_spec = NarrativeDesignOutputSchema.model_validate_json(in_json)
        except ValidationError as e:
            print(e)
            return
        
        sb_agent_input: str = get_sb_agent_input(nd_spec, scene_uuid)

        agent: Agent = Agent[NarrativeDesignOutputSchema](
            name="scene_beat_agent",
            instructions=get_sb_agent_instructions,
            output_type=SceneBeatSheet,
            model="gpt-5.4", # maybe overkill? Can we trust mini with this task?
            model_settings=ModelSettings(
                reasoning=Reasoning(
                    effort='high',
                    summary='detailed'
                )
            ) # do we really need ModelSettings here? if not I'll remove it
        )

        run_result: RunResult = await Runner.run(
            agent,
            input=sb_agent_input,
            context=nd_spec
        )

        return run_result.final_output


async def main():

    # use locally stored Narrative Design Agent output for testing...
    try:
        with open('dummy_data.json', 'r') as f:
            json_str = f.read().strip()

        nd_output: NarrativeDesignOutputSchema = NarrativeDesignOutputSchema.model_validate_json(json_str)
        intro_uuid = nd_output.intro_scene.scene_data.uuid
        first_scene_uuid = nd_output.act_one[0].scene_data.uuid

        bs_gather = asyncio.gather(
            SceneBeatAgent().run_workflow(json_str, intro_uuid),
            SceneBeatAgent().run_workflow(json_str, first_scene_uuid)
        )

        beat_sheets: list[SceneBeatSheet] = await bs_gather
        bs_intro: SceneBeatSheet = beat_sheets[0]
        bs_first: SceneBeatSheet = beat_sheets[1]

        with open('dummy_intro_beats.json', 'w') as f:
            f.write(bs_intro.model_dump_json(indent=2))
        with open('dummy_scene1_beats.json', 'w') as g:
            g.write(bs_first.model_dump_json(indent=2))

        #print(f"===INTRO===\n\n{beat_sheets[0].model_dump_json(indent=2)}\n\n")
        #print(f"===FIRST SCENE===\n\n{beat_sheets[1].model_dump_json(indent=2)}\n\n")

    except Exception as e:
        print(e)

if __name__ == "__main__":
    asyncio.run(main())