# src/scene_beat_agent.py
# to unit test, run as module in the terminal from the project root:
  # $ python3 -m src.scene_beat_agent
# ^^This uses dummy_data.json, generated by running the narrative design agent main()

from pydantic import BaseModel, Field, ValidationError
from typing import Literal, Optional
from agents import Agent, Runner, RunResult, RunContextWrapper
from pathlib import Path
from dotenv import load_dotenv
import json
import sys
import asyncio

# LOCAL MODULES
SRC_ROOT: Path = Path(__file__).parent # the src/ folder
TOOLS_PATH: Path = SRC_ROOT / "tools"

sys.path.insert(0, str(SRC_ROOT))
sys.path.insert(0, str(TOOLS_PATH))

from narrative_design_agent import NarrativeDesignOutputSchema, Scene, SceneData, Location, LocationData, CharacterData

load_dotenv()


def scene_beat_instructons(
        wrapper: RunContextWrapper[NarrativeDesignOutputSchema],
        agent: Agent[NarrativeDesignOutputSchema],
        scene_uuid: str
) -> str:
    # extract all the relevant data from the context
    nd_spec: NarrativeDesignOutputSchema = wrapper.context
    scene_catalog       = nd_spec.get_scene_catalog() # scenes indexed by UUID
    character_catalog   = nd_spec.get_character_catalog() # characters indexed by UUID
    location_catalog    = nd_spec.get_location_catalog() # locations indexed by UUID
    readable_spec       = nd_spec.human_readable()

    if not scene_uuid in scene_catalog:
        raise ValidationError ("scene_uuid not in catalogue")
    scene_data: SceneData = SceneData.model_validate(scene_catalog[scene_uuid])

    scene_name: str = scene_data.scene_name
    narrative_summary: str = scene_data.narrtive_summary

    location_uuid: str = scene_data.location_uuid
    location_data: LocationData = LocationData.model_validate(location_catalog[location_uuid])

    npc_uuids = []
    npc_datas: list [CharacterData] = []
    if 'non_player_character_uuids' in scene_data.__dict__:
        if not scene_data.non_player_character_uuids is None:
            npc_uuids = scene_data.non_player_character_uuids
            for id in npc_uuids:
                npc_datas.append(CharacterData.model_validate(character_catalog[id]))
    
    player_uuid = nd_spec.player_character.character_data.uuid
    player_data: CharacterData = CharacterData.model_validate(character_catalog[player_uuid])
    
    # write the promt string
    prompt_str = f""""""

    # deliver the prompt
    return prompt_str

scene_beat_agent: Agent = Agent(
    name="scene_beat_agent",
    instructions="You write the scene beats for the visual novel",
    model="gpt-5.4-mini"
    # TODO: ^^define the actual agent, and better instructions. We'll get to that later
)
# Use SceneBeatSheet instead...
# class SceneBeatAgentOutputSchema(BaseModel):
#     story_title: str = Field(..., description="The title of the story. This is copied directly from the workflow input")
#     # TODO: How to structure this?

class SceneBeatAgent():
    def __init__(self):
        self.agent: Agent = scene_beat_agent

    async def run_workflow(self, in_json: str, scene_uuid: str):

        try:
            nd_spec = NarrativeDesignOutputSchema.model_validate_json(in_json)
        except ValidationError as e:
            print(e)
            return
        
        # print(f"Coming soon: The SceneBeatAgent writes scene beats for {nd_spec.story_title}!!!")
        # print(f"===SCENE CATALOG===\n{json.dumps(nd_spec.get_scene_catalog(), indent=2)}")
        # print(f"===CHARACTER CATALOG===\n{json.dumps(nd_spec.get_character_catalog(), indent=2)}")
        # print(f"===LOCATION CATALOG===\n{json.dumps(nd_spec.get_location_catalog(), indent=2)}")
        # All ^^this works

        # scene_catalog = nd_spec.get_scene_catalog()
        # if not scene_uuid in scene_catalog:
        #     raise ValidationError ("scene_uuid not in catalogue")
        # scene_data: SceneData = SceneData.model_validate(scene_catalog[scene_uuid])
        # print(scene_data.scene_name)
        # All ^^this works

        # scene_catalog       = nd_spec.get_scene_catalog() # scenes indexed by UUID
        # character_catalog   = nd_spec.get_character_catalog() # characters indexed by UUID
        # location_catalog    = nd_spec.get_location_catalog() # locations indexed by UUID
        # readable_spec       = nd_spec.human_readable()

        # if not scene_uuid in scene_catalog:
        #     raise ValidationError ("scene_uuid not in catalogue")
        # scene_data: SceneData = SceneData.model_validate(scene_catalog[scene_uuid])

        # scene_name: str = scene_data.scene_name
        # narrative_summary: str = scene_data.narrtive_summary

        # location_uuid: str = scene_data.location_uuid
        # location_data: LocationData = LocationData.model_validate(location_catalog[location_uuid])

        # npc_uuids = []
        # npc_datas: list [CharacterData] = []
        # if 'non_player_character_uuids' in scene_data.__dict__:
        #     if not scene_data.non_player_character_uuids is None:
        #         npc_uuids = scene_data.non_player_character_uuids
        #         for id in npc_uuids:
        #             npc_datas.append(CharacterData.model_validate(character_catalog[id]))
        
        # player_uuid = nd_spec.player_character.character_data.uuid
        # player_data: CharacterData = CharacterData.model_validate(character_catalog[player_uuid])

        # print(f"\n\nI will write the scene beats for {scene_name}.\n")
        # print(f"Here is the narrative summary from the Narrative Designer:\n{narrative_summary}\n")
        # print(f"Location name: {location_data.name}\n")
        # print(f"Location desc: {location_data.location_image_prompt}\n")
        # print(f"Player character name: {player_data.name}")
        # print(f"Player character desc: {player_data.portrait_image_prompt}")
        # print(f"Player character dialogue examples:\n")
        # for line in player_data.dialogue_examples:
        #     print(f"  -'{line}'")

        # if len(npc_uuids) > 0:
        #     print(f"\nHere are the NPCs:\n")
        #     for data in npc_datas:
        #         print(f"  -'{data.name}'")
        # All ^^this works


async def main():

    try:
        with open('dummy_data.json', 'r') as f:
            json_str = f.read().strip()

        nd_output: NarrativeDesignOutputSchema = NarrativeDesignOutputSchema.model_validate_json(json_str)
        intro_uuid          = nd_output.intro_scene.scene_data.uuid
        first_scene_uuid    = nd_output.act_one[0].scene_data.uuid

        await SceneBeatAgent().run_workflow(json_str, intro_uuid)
        await SceneBeatAgent().run_workflow(json_str, first_scene_uuid)

    except Exception as e:
        print(e)

if __name__ == "__main__":
    asyncio.run(main())


#=====
# WIP
#=====

# class SceneBeat(BaseModel):
#     beat_index: int = Field(description="1-based position of this beat in the scene.")
#     beat_id: str = Field(description="Stable ID like intro_01_beat_01.")
#     purpose: str = Field(description="Why this beat exists in the scene.")
#     summary: str = Field(description="What happens in this beat, in 1-3 sentences.")
#     locationuuid: str = Field(description="The location where this beat takes place.")
#     present_character_uuids: list[str] = Field(
#         description="Player character plus any NPCs actively present in the beat."
#     )
#     focal_character_uuid: Optional[str] = Field(
#         default=None,
#         description="The character driving the beat emotionally or narratively."
#     )
#     mood: str = Field(description="The emotional tone of the beat.")
#     revelation: Optional[str] = Field(
#         default=None,
#         description="New information learned in this beat, if any."
#     )
#     tension_change: Literal["rise", "fall", "twist", "hold"] = Field(
#         description="How this beat changes dramatic tension."
#     )
#     player_goal: Optional[str] = Field(
#         default=None,
#         description="What the player character is trying to do in this beat."
#     )
#     interactive: bool = Field(
#         description="Whether this beat contains a player choice or interactive moment."
#     )
#     choice_prompt: Optional[str] = Field(
#         default=None,
#         description="Short description of the player decision, if interactive."
#     )
#     branch_outcomes: Optional[list[str]] = Field(
#         default=None,
#         description="High-level outcomes for the available choices, if interactive."
#     )
#     exit_state: str = Field(
#         description="What has changed by the end of the beat."
#     )


# class SceneBeatAgentInput(BaseModel):
#     storytitle: str
#     synopsis: str
#     playercharacter: PlayerCharacter
#     nonplayercharacters: list[NonPlayerCharacter]
#     locations: list[Location]
#     introscene: Scene
#     actone: list[Scene]
#     acttwo: list[Scene]
#     actthree: list[Scene]
#     outroscene: Scene
#     target_scene_id: str


# # Output shape:

# class SceneBeatSheet(BaseModel):
#     storytitle: str
#     scene_id: str = Field(description="Stable ID like intro or act1_scene1.")
#     source_scene_summary: str
#     locationuuid: str
#     playercharacter_uuid: str
#     nonplayercharacteruuids: list[str]
#     dramatic_question: str = Field(
#         description="The core uncertainty driving the scene."
#     )
#     scene_goal: str = Field(
#         description="What the player character wants in the scene."
#     )
#     scene_turn: str = Field(
#         description="What changes by the end of the scene."
#     )
#     beats: list[SceneBeat] = Field(
#         description="Ordered beat list for this scene, usually 5-8 beats."
#     )