# src/scene_beat_agent.py
# to unit test, run as module in the terminal from the project root:
  # $ python3 -m src.scene_beat_agent
# ^^This uses dummy_data.json, generated by running the narrative design agent main()

from pydantic import BaseModel, Field, ValidationError
from typing import Literal, Optional
from agents import Agent, Runner, RunResult
from pathlib import Path
from dotenv import load_dotenv
import sys
import asyncio

# LOCAL MODULES
SRC_ROOT: Path = Path(__file__).parent # the src/ folder
TOOLS_PATH: Path = SRC_ROOT / "tools"

sys.path.insert(0, str(SRC_ROOT))
sys.path.insert(0, str(TOOLS_PATH))

from narrative_design_agent import NarrativeDesignOutputSchema, Scene, SceneData, Location, LocationData

load_dotenv()

scene_beat_agent: Agent = Agent(
    name="scene_beat_agent",
    instructions="You write the scene beats for the visual novel",
    model="gpt-5.4-mini"
    # TODO: ^^define the actual agent, and better instructions. We'll get to that later
)
# Use SceneBeatSheet instead...
# class SceneBeatAgentOutputSchema(BaseModel):
#     story_title: str = Field(..., description="The title of the story. This is copied directly from the workflow input")
#     # TODO: How to structure this?

class SceneBeatAgent():
    def __init__(self):
        self.agent: Agent = scene_beat_agent

    async def run_workflow(self, in_json: str):

        try:
            nd_spec = NarrativeDesignOutputSchema.model_validate_json(in_json)
        except ValidationError as e:
            print(e)
            return
        
        print(f"Coming soon: The SceneBeatAgent writes scene beats for {nd_spec.story_title}!!!")
        pass



async def main():

    try:
        with open('dummy_data.json', 'r') as f:
            json_str = f.read().strip()
        await SceneBeatAgent().run_workflow(json_str)
    except Exception as e:
        print(e)

if __name__ == "__main__":
    asyncio.run(main())


#=====
# WIP
#=====

# class SceneBeat(BaseModel):
#     beat_index: int = Field(description="1-based position of this beat in the scene.")
#     beat_id: str = Field(description="Stable ID like intro_01_beat_01.")
#     purpose: str = Field(description="Why this beat exists in the scene.")
#     summary: str = Field(description="What happens in this beat, in 1-3 sentences.")
#     locationuuid: str = Field(description="The location where this beat takes place.")
#     present_character_uuids: list[str] = Field(
#         description="Player character plus any NPCs actively present in the beat."
#     )
#     focal_character_uuid: Optional[str] = Field(
#         default=None,
#         description="The character driving the beat emotionally or narratively."
#     )
#     mood: str = Field(description="The emotional tone of the beat.")
#     revelation: Optional[str] = Field(
#         default=None,
#         description="New information learned in this beat, if any."
#     )
#     tension_change: Literal["rise", "fall", "twist", "hold"] = Field(
#         description="How this beat changes dramatic tension."
#     )
#     player_goal: Optional[str] = Field(
#         default=None,
#         description="What the player character is trying to do in this beat."
#     )
#     interactive: bool = Field(
#         description="Whether this beat contains a player choice or interactive moment."
#     )
#     choice_prompt: Optional[str] = Field(
#         default=None,
#         description="Short description of the player decision, if interactive."
#     )
#     branch_outcomes: Optional[list[str]] = Field(
#         default=None,
#         description="High-level outcomes for the available choices, if interactive."
#     )
#     exit_state: str = Field(
#         description="What has changed by the end of the beat."
#     )


# class SceneBeatAgentInput(BaseModel):
#     storytitle: str
#     synopsis: str
#     playercharacter: PlayerCharacter
#     nonplayercharacters: list[NonPlayerCharacter]
#     locations: list[Location]
#     introscene: Scene
#     actone: list[Scene]
#     acttwo: list[Scene]
#     actthree: list[Scene]
#     outroscene: Scene
#     target_scene_id: str


# # Output shape:

# class SceneBeatSheet(BaseModel):
#     storytitle: str
#     scene_id: str = Field(description="Stable ID like intro or act1_scene1.")
#     source_scene_summary: str
#     locationuuid: str
#     playercharacter_uuid: str
#     nonplayercharacteruuids: list[str]
#     dramatic_question: str = Field(
#         description="The core uncertainty driving the scene."
#     )
#     scene_goal: str = Field(
#         description="What the player character wants in the scene."
#     )
#     scene_turn: str = Field(
#         description="What changes by the end of the scene."
#     )
#     beats: list[SceneBeat] = Field(
#         description="Ordered beat list for this scene, usually 5-8 beats."
#     )